version: '3.8'

services:
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    networks:
      - redis-network
    volumes:
      - redis-data:/data
    
  celery:
    build: ./celery-app
    command: celery -A tasks worker --loglevel=info # example
    depends_on:
      - redis
    networks:
      - redis-network

  bot:
    build: ./bot
    command: python run.py
    depends_on:
      - redis
    networks:
      - redis-network

networks:
  redis-network:
    driver: bridge

volumes:
  redis-data: